# Generated by Django 4.2.5 on 2023-10-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(blank=True, max_length=20, null=True)),
                ('Last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('Email_id', models.CharField(blank=True, max_length=30, null=True)),
                ('Address', models.CharField(blank=True, max_length=50, null=True)),
                ('City', models.CharField(blank=True, max_length=40, null=True)),
                ('Country', models.CharField(blank=True, max_length=20, null=True)),
                ('Zip_code', models.IntegerField(blank=True, null=True)),
                ('Telephone', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
