# Generated by Django 4.2.5 on 2023-09-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatavail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Product_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Product_Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_Price', models.IntegerField(blank=True, null=True)),
                ('Product_Image', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
    ]
